version: "3"

services:
  web:
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - .:/dockerized_app
  
  mongo:
    image: mongo:4.4.8
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: